TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += mettlerToledo.template
DB += mettlerToledoWeightResponse.template
DB += mettlerToledoWeightResponseWrapper.template
DB += mettlerToledoStatusResponse.template
DB += mettlerToledoStatusResponseWrapper.template
DB += mettlerToledoAlarmLimits.template

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

